platform: linux

inputs:
  - name: repo

params:
  CARGO_REGISTRIES_ANCALAGON_INDEX:
  CARGO_REGISTRIES_ANCALAGON_TOKEN:
  EXTRA_CARGO_BUILD_FLAGS: ""
  EXTRA_CARGO_TEST_FLAGS: ""

caches:
  # yeah, I'm not sure how I feel about caching the registry like this,
  # but concourse only allows relative paths instead of absolute ones
  - path: ../../../usr/local/cargo/registry

  # cache the target folder to speed up builds
  - path: repo/target

run:
  dir: repo
  path: /bin/sh
  args:
    - "-c"
    - |
      set -ex
      cargo build --verbose ${EXTRA_CARGO_BUILD_FLAGS}
      cargo test --verbose ${EXTRA_CARGO_TEST_FLAGS}
