resource_types:
  - name: slack-alert
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource

resources:
  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/rust-ci.git
      ignore_paths:
        - 'README.md'

  - name: stable-alpine
    type: registry-image
    source:
      repository: rust
      tag: ((rust.version))-alpine
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: stable-slim
    type: registry-image
    source:
      repository: rust
      tag: ((rust.version))-slim
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: nightly-slim
    type: registry-image
    icon: docker
    source:
      repository: rustlang/rust
      tag: nightly-slim
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: output-alpine
    type: registry-image
    source:
      repository: mattcl/ci-rust-alpine
      tag: ((rust.version))
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: output-slim
    type: registry-image
    source:
      repository: mattcl/ci-rust-slim
      tag: ((rust.version))
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: output-nightly
    type: registry-image
    source:
      repository: mattcl/ci-rust-nightly
      tag: latest
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: notify
    type: slack-alert
    source:
      url: ((slack.webhook-url))
      channel: ((slack.channel))
      concourse_url: ((server.url))

jobs:
  - name: alpine
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: stable-alpine
          trigger: true
          params:
            skip_download: true


      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: ci
          outputs:
            - name: image
          params:
            CONTEXT: ci/docker
            DOCKERFILE: ci/docker/alpine.Dockerfile
          run:
            path: build

      - put: output-alpine
        params:
          image: image/image.tar
          additional_tags: stable-alpine/tag

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored

  - name: slim
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: stable-slim
          trigger: true
          params:
            skip_download: true

      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: ci
          outputs:
            - name: image
          params:
            CONTEXT: ci/docker
            DOCKERFILE: ci/docker/slim.Dockerfile
          run:
            path: build

      - put: output-slim
        params:
          image: image/image.tar
          additional_tags: stable-slim/tag

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored

  - name: nightly
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: nightly-slim
          trigger: true
          params:
            skip_download: true

      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: ci
          outputs:
            - name: image
          params:
            CONTEXT: ci/docker
            DOCKERFILE: ci/docker/nightly.Dockerfile
          run:
            path: build

      - put: output-nightly
        params:
          image: image/image.tar

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored
