resource_types:
  - name: slack-alert
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource

resources:
  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/rust-ci.git
      ignore_paths:
        - 'README.md'

  - name: ((lib.name))
    type: git
    icon: github
    source:
      uri: ((lib.repo.uri))
      ignore_paths:
        - 'README.md'

  - name: nightly
    type: registry-image
    icon: docker
    source:
      repository: rustlang/rust
      tag: nightly-slim
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: slim
    type: registry-image
    icon: docker
    source:
      repository: mattcl/ci-rust-slim
      tag: ((rust.version))
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: alpine
    type: registry-image
    icon: docker
    source:
      repository: mattcl/ci-rust-alpine
      tag: ((rust.version))
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: notify
    type: slack-alert
    source:
      url: ((slack.webhook-url))
      channel: ((slack.channel))
      concourse_url: ((server.url))

jobs:
  - name: stable-alpine
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: ((lib.name))
          trigger: true
        - get: alpine
          trigger: true

      - task: test
        image: alpine
        tags:
          - internal
        file: ci/tasks/lint-and-test.yaml
        input_mapping:
          repo: ((lib.name))
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon-registry.index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon-registry.token))
          EXTRA_CARGO_BUILD_FLAGS: "((alpine.cargo.extra-build-flags))"
          EXTRA_CARGO_TEST_FLAGS: "((alpine.cargo.extra-test-flags))"

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored

  - name: stable-slim
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: ((lib.name))
          trigger: true
        - get: slim
          trigger: true

      - task: test
        image: slim
        tags:
          - internal
        file: ci/tasks/lint-and-test.yaml
        input_mapping:
          repo: ((lib.name))
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon-registry.index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon-registry.token))
          EXTRA_CARGO_BUILD_FLAGS: "((slim.cargo.extra-build-flags))"
          EXTRA_CARGO_TEST_FLAGS: "((slim.cargo.extra-test-flags))"

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored

  - name: nightly
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: ((lib.name))
          trigger: true
        - get: nightly
          trigger: true

      - task: test
        image: nightly
        tags:
          - internal
        file: ci/tasks/lint-and-test.yaml
        input_mapping:
          repo: ((lib.name))
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon-registry.index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon-registry.token))
          EXTRA_CARGO_BUILD_FLAGS: "((nightly.cargo.extra-build-flags))"
          EXTRA_CARGO_TEST_FLAGS: "((nightly.cargo.extra-test-flags))"
          LINT: "0"

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored

  - name: max-vers-msrv
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: ((lib.name))
          trigger: true
          passed:
            - stable-alpine
            - stable-slim

      - task: check-msrv
        tags:
          - internal
        file: ci/tasks/msrv.yaml
        input_mapping:
          repo: ((lib.name))
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon-registry.index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon-registry.token))

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored

  - name: min-vers-msrv
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: ((lib.name))
          trigger: true
          passed:
            - nightly
        - get: nightly
          trigger: false
          passed:
            - nightly

      - task: find-min-versions
        image: nightly
        tags:
          - internal
        file: ci/tasks/min-versions.yaml
        input_mapping:
          repo: ((lib.name))
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon-registry.index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon-registry.token))

      - task: check-msrv
        tags:
          - internal
        file: ci/tasks/msrv.yaml
        input_mapping:
          repo: repo
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon-registry.index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon-registry.token))
          UPDATE_DEPS: "0"

    on_success:
      put: notify
      params:
        alert_type: success
    on_failure:
      put: notify
      params:
        alert_type: failed
    on_abort:
      put: notify
      params:
        alert_type: aborted
    on_error:
      put: notify
      params:
        alert_type: errored
