resources:
  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/rust-ci.git
      ignore_paths:
        - 'README.md'

  - name: ((lib.name))
    type: git
    icon: github
    source:
      uri: ((lib.repo.uri))
      ignore_paths:
        - 'README.md'

  - name: nightly
    type: registry-image
    source:
      repository: rustlang/rust
      tag: nightly-slim
      username: ((dockerhub.user))
      password: ((dockerhub.token))

  - name: stable
    type: registry-image
    source:
      repository: rust
      tag: ((rust.version))-slim
      username: ((dockerhub.user))
      password: ((dockerhub.token))

jobs:
  - name: stable
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: ((lib.name))
          trigger: true
        - get: stable
          trigger: true

      - task: test
        image: stable
        tags:
          - internal
        file: ci/tasks/lint-and-test.yaml
        input_mapping:
          repo: ((lib.name))
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon-registry.index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon-registry.token))

  - name: nightly
    build_log_retention:
      days: 2
      builds: 20
      minimum_succeeded_builds: 1
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: ((lib.name))
          trigger: true
        - get: nightly
          trigger: true

      - task: test
        image: nightly
        tags:
          - internal
        file: ci/tasks/lint-and-test.yaml
        input_mapping:
          repo: ((lib.name))
        params:
          CARGO_REGISTRIES_ANCALAGON_INDEX: ((ancalagon.registry-index))
          CARGO_REGISTRIES_ANCALAGON_TOKEN: ((ancalagon.registry-token))
